### ISSUE TITLE
unhandled exception in sdk

### ISSUE THREAD

**Issue by rami3sam** [tutipay/java-sdk#28]
FATAL EXCEPTION: Thread-18
                                                                                                    Process: com.tutipay.app.alpha, PID: 12721
                                                                                                    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
                                                                                                    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:963)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:928)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:877)
                                                                                                    	at com.tuti.api.TutiApiClient.parseResponse(TutiApiClient.java:420)
                                                                                                    	at com.tuti.api.TutiApiClient.lambda$sendRequest$0$com-tuti-api-TutiApiClient(TutiApiClient.java:391)
                                                                                                    	at com.tuti.api.TutiApiClient$$ExternalSyntheticLambda0.run(Unknown Source:18)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
                                                                                                    	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
                                                                                                    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:963) 
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:928) 
                                                                                                    	at com.google.gson.Gson.fromJson(Gson.java:877) 
                                                                                                    	at com.tuti.api.TutiApiClient.parseResponse(TutiApiClient.java:420) 
                                                                                                    	at com.tuti.api.TutiApiClient.lambda$sendRequest$0$com-tuti-api-TutiApiClient(TutiApiClient.java:391) 
                                                                                                    	at com.tuti.api.TutiApiClient$$ExternalSyntheticLambda0.run(Unknown Source:18) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 

when the server returns an error that doesn't conform to json format the sdk can't parse it and throws an exception

the responsible snippet is below

private boolean isTypeStringOrNull(Type type) {
        return (type == String.class || type == null);
}

**Comment by rami3sam** [comment]
it should recieve an object as a parameter
and check if the object is null or that it's type is string
the above code that i wrote isn't working

**Comment by rami3sam** [comment]
below is a candidate solution

private boolean isTypeStringOrNull(Object object) {
if(object == null)
return true;

if(object instanceof String)
return true;
}

**Comment by rami3sam** [comment]
bear in mind that's what i wrote is just psuedo-code and not an actual solution
